#!/usr/bin/env bash
#
# Haas Appliance - Firewall Automation Installer (Config-File Architecture)
#
# This installer:
#   - Assumes it is run from the repo root: Haas_Data_collect/
#   - Detects the repo directory dynamically (can be anywhere)
#   - Writes /etc/haas-firewall.conf with:
#       CSV_PATH, BACKUP_DIR, HAAS_MACHINES_SUBNET_V4, HAAS_MACHINES_SUBNET_V6
#   - Installs firewall scripts into /usr/local/sbin
#   - Installs systemd service + timer
#   - Installs Cockpit extension
#   - Creates the backup directory in the repo
#   - Triggers an initial firewall configuration via systemd
#
# It does NOT modify or delete anything inside the repo.
#

set -euo pipefail

echo "[*] Starting Haas Firewall installation..."

########################################
# DETECT REPO DIRECTORY
########################################

REPO_DIR="$(pwd)"
REPO_NAME="$(basename "$REPO_DIR")"

if [[ "$REPO_NAME" != "Haas_Data_collect" ]]; then
    echo "[WARNING] Repo root is expected to be named 'Haas_Data_collect', but got: '$REPO_NAME'"
    echo "          Proceeding anyway, using current directory as repo root."
fi

echo "[*] Repo directory detected as: $REPO_DIR"

CSV_PATH="$REPO_DIR/users.csv"
BACKUP_DIR="$REPO_DIR/backups"
COCKPIT_SRC="$REPO_DIR/cockpit"

########################################
# VERIFY REQUIRED FILES
########################################

REQUIRED_FILES=(
  "configure_ufw_from_csv.sh"
  "validate_users_csv.sh"
  "haas-firewall.service"
  "haas-firewall.timer"
)

echo "[*] Verifying required files in repo..."

for f in "${REQUIRED_FILES[@]}"; do
  if [[ ! -f "$REPO_DIR/$f" ]]; then
    echo "[ERROR] Missing required file: $REPO_DIR/$f"
    exit 1
  fi
done

if [[ ! -f "$CSV_PATH" ]]; then
  echo "[ERROR] CSV file not found at: $CSV_PATH"
  echo "        Create users.csv with header: username,ip_address,role"
  exit 1
fi

if [[ ! -d "$COCKPIT_SRC" ]]; then
  echo "[ERROR] Cockpit directory missing: $COCKPIT_SRC"
  exit 1
fi

for f in manifest.json index.html haas-firewall.js icon.png; do
  if [[ ! -f "$COCKPIT_SRC/$f" ]]; then
    echo "[ERROR] Missing Cockpit file: $COCKPIT_SRC/$f"
    exit 1
  fi
done

echo "[OK] All required repo files are present."

########################################
# WRITE CONFIG FILE
########################################

CONFIG_FILE="/etc/haas-firewall.conf"

echo "[*] Writing config file: $CONFIG_FILE"

sudo bash -c "cat > '$CONFIG_FILE'" <<EOF
# Haas Firewall Appliance Configuration
# Generated by haas_firewall_install.sh
#
# CSV_PATH:
#   Path to the users.csv file that controls firewall rules.
#
# BACKUP_DIR:
#   Directory where CSV backups will be stored.
#
# HAAS_MACHINES_SUBNET_V4 / HAAS_MACHINES_SUBNET_V6:
#   Optional subnets for Haas CNC machines.
#   If left empty, no subnet-wide Haas rules are applied.
#   Example:
#     HAAS_MACHINES_SUBNET_V4="192.168.10.0/24"

CSV_PATH="$CSV_PATH"
BACKUP_DIR="$BACKUP_DIR"

HAAS_MACHINES_SUBNET_V4=""
HAAS_MACHINES_SUBNET_V6=""
EOF

sudo chmod 644 "$CONFIG_FILE"

echo "[OK] Config file written."

########################################
# INSTALL SCRIPTS
########################################

echo "[*] Installing firewall scripts into /usr/local/sbin..."

sudo cp "$REPO_DIR/configure_ufw_from_csv.sh" /usr/local/sbin/
sudo cp "$REPO_DIR/validate_users_csv.sh" /usr/local/sbin/

sudo chmod +x /usr/local/sbin/configure_ufw_from_csv.sh
sudo chmod +x /usr/local/sbin/validate_users_csv.sh

if [[ ! -x /usr/local/sbin/configure_ufw_from_csv.sh ]]; then
  echo "[ERROR] Failed to install configure_ufw_from_csv.sh"
  exit 1
fi

if [[ ! -x /usr/local/sbin/validate_users_csv.sh ]]; then
  echo "[ERROR] Failed to install validate_users_csv.sh"
  exit 1
fi

echo "[OK] Firewall scripts installed."

########################################
# INSTALL SYSTEMD UNITS
########################################

echo "[*] Installing systemd service and timer..."

sudo cp "$REPO_DIR/haas-firewall.service" /etc/systemd/system/
sudo cp "$REPO_DIR/haas-firewall.timer" /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable haas-firewall.service
sudo systemctl enable --now haas-firewall.timer

echo "[OK] Systemd service and timer installed and enabled."

########################################
# INSTALL COCKPIT EXTENSION
########################################

COCKPIT_DST="/usr/share/cockpit/haas-firewall"

echo "[*] Installing Cockpit extension to $COCKPIT_DST..."

sudo mkdir -p "$COCKPIT_DST"
sudo cp "$COCKPIT_SRC"/* "$COCKPIT_DST"/

echo "[*] Restarting Cockpit..."
sudo systemctl restart cockpit
echo "[OK] Cockpit extension installed and Cockpit restarted."

########################################
# ENSURE BACKUP DIRECTORY EXISTS
########################################

echo "[*] Ensuring backup directory exists in repo: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

echo "[OK] Backup directory ready."

########################################
# RUN INITIAL FIREWALL CONFIG VIA SYSTEMD
########################################

echo "[*] Running initial firewall configuration via haas-firewall.service..."
sudo systemctl start haas-firewall.service || true

echo ""
echo "=============================================="
echo "[SUCCESS] Haas Firewall installation complete."
echo "=============================================="
echo ""
echo "Repo root:     $REPO_DIR"
echo "CSV Path:      $CSV_PATH"
echo "Backup Dir:    $BACKUP_DIR"
echo "Config File:   $CONFIG_FILE"
echo "Scripts:       /usr/local/sbin/configure_ufw_from_csv.sh"
echo "               /usr/local/sbin/validate_users_csv.sh"
echo "Systemd:       /etc/systemd/system/haas-firewall.service"
echo "               /etc/systemd/system/haas-firewall.timer"
echo "Cockpit UI:    /usr/share/cockpit/haas-firewall/"
echo ""
echo "To enable a Haas subnet later, edit:"
echo "$CONFIG_FILE"
echo ""
echo "set HAAS_MACHINES_SUBNET_V4="" to your CNC machines' IPv4 subnet"
echo "set HAAS_MACHINES_SUBNET_V6="" to your CNC machines' IPv6 subnet (if applicable)"
echo ""
echo "Check firewall status with:"
echo "  sudo ufw status numbered"
echo ""
echo "Current UFW rules:"
sudo ufw status numbered
echo ""
