#!/usr/bin/env bash
#
# Haas Appliance - Firewall Automation Installer (Config-File Architecture)
#
# This installer:
#   - Assumes it is run from the repo root: Haas_Data_collect/
#   - Detects the repo directory dynamically (can be anywhere)
#   - Writes /etc/haas-firewall.conf with:
#       CSV_PATH, BACKUP_DIR, HAAS_MACHINES_SUBNET_V4, HAAS_MACHINES_SUBNET_V6, SSH_PORT
#   - Copies issue.net to /etc/issue.net (Pre-logon banner)
#   - Installs firewall scripts into /usr/local/sbin
#        configure_ufw_from_csv.sh
#        validate_users_csv.sh
#        rollback_csv.sh
#        build-nmap.sh
#     Install csvlens binary to /usr/local/sbin
#        csvlens
#   - Copies build-nmap.sh to /usr/local/sbin
#   - Installs the latest nmap
#   - Installs systemd firewall service + timer
#   - Installs Samba server and updates /etc/samba/smb.conf
#       sets security and creates the "[Haas]" share
#   - Installs Cockpit extension
#   - Installs the "micro" cli text editor
#   - Installs the "fresh" cli text editor
#   - Creates the backup directory in the repo
#   - Triggers an initial firewall configuration via systemd
#
# It does NOT modify or delete anything inside the repo.
#

set -euo pipefail

echo "[*] Starting Haas Firewall installation..."

########################################
# DETECT REPO DIRECTORY
########################################

REPO_DIR="$(pwd)"
REPO_NAME="$(basename "$REPO_DIR")"

if [[ "$REPO_NAME" != "Haas_Data_collect" ]]; then
    echo "[WARNING] Repo root is expected to be named 'Haas_Data_collect', but got: '$REPO_NAME'"
    echo "          Proceeding anyway, using current directory as repo root."
fi

echo "[*] Repo directory detected as: $REPO_DIR"

BACKUP_DIR="$REPO_DIR/backups"
COCKPIT_SRC="$REPO_DIR/cockpit"
CSV_PATH="$REPO_DIR/users.csv"

########################################
# VERIFY REQUIRED FILES
########################################

REQUIRED_FILES=(
  "configure_ufw_from_csv.sh"
  "validate_users_csv.sh"
  "haas-firewall.service"
  "haas-firewall.timer"
  "rollback_csv.sh"
  "build-nmap.sh"
  "issue.net"
)

echo "[*] Verifying required files in repo..."

for f in "${REQUIRED_FILES[@]}"; do
  if [[ ! -f "$REPO_DIR/$f" ]]; then
    echo "[ERROR] Missing required file: $REPO_DIR/$f"
    exit 1
  fi
done

if [[ ! -f "$CSV_PATH" ]]; then
  echo "[ERROR] CSV file not found at: $CSV_PATH"
  echo "        Create users.csv with header: username,ip_address,role"
  exit 1
fi

if [[ ! -d "$COCKPIT_SRC" ]]; then
  echo "[ERROR] Cockpit directory missing: $COCKPIT_SRC"
  exit 1
fi

for f in manifest.json index.html haas-firewall.js haas-firewall.css icon.png; do
  if [[ ! -f "$COCKPIT_SRC/$f" ]]; then
    echo "[ERROR] Missing Cockpit file: $COCKPIT_SRC/$f"
    exit 1
  fi
done

echo "[OK] All required repo files are present."

########################################
# WRITE CONFIG FILE
########################################

CONFIG_FILE="/etc/haas-firewall.conf"

echo "[*] Writing config file: $CONFIG_FILE"

sudo bash -c "cat > '$CONFIG_FILE'" <<EOF
# Haas Firewall Appliance Configuration
# Generated by haas_firewall_install.sh
#
# CSV_PATH:
#   Path to the users.csv file that controls firewall rules.
#
# BACKUP_DIR:
#   Directory where CSV backups will be stored.
#
# HAAS_MACHINES_SUBNET_V4 / HAAS_MACHINES_SUBNET_V6:
#   Optional subnets for Haas CNC machines.
#   If left empty, no subnet-wide Haas rules are applied.
#   Example:
#     HAAS_MACHINES_SUBNET_V4="192.168.10.0/24"

CSV_PATH="$CSV_PATH"
BACKUP_DIR="$BACKUP_DIR"

HAAS_MACHINES_SUBNET_V4=""
HAAS_MACHINES_SUBNET_V6=""
SSH_PORT="22"
EOF

sudo chmod 644 "$CONFIG_FILE"

echo "[OK] Config file written."

########################################
# INSTALL SCRIPTS
########################################

echo "[*] Installing firewall scripts into /usr/local/sbin..."

sudo cp "$REPO_DIR/configure_ufw_from_csv.sh" /usr/local/sbin/
sudo cp "$REPO_DIR/validate_users_csv.sh" /usr/local/sbin/
sudo cp "$REPO_DIR/rollback_csv.sh" /usr/local/sbin/
sudo cp "$REPO_DIR/build-nmap.sh" /usr/local/sbin/
sudo cp "$REPO_DIR/csvlens" /usr/local/sbin/
sudo cp "$REPO_DIR/issue.net" /etc/issue.net

# Update the banner setting in sshd_config
if [ -f /etc/issue.net ] && grep -q "^Banner" /etc/ssh/sshd_config && sudo sshd -t; then
    echo "✅ Success: /etc/issue.net exists and SSH config is valid."
else
    echo "❌ Error: Missing file or invalid SSH config!"
    [ ! -f /etc/issue.net ] && echo "   -> /etc/issue.net is missing."
    ! grep -q "^Banner" /etc/ssh/sshd_config && echo "   -> Banner line not found in config."
    ! sudo sshd -t && echo "   -> sshd syntax error detected."
    exit 1
fi
sleep 5

sudo chmod +x /usr/local/sbin/configure_ufw_from_csv.sh
sudo chmod +x /usr/local/sbin/validate_users_csv.sh
sudo chmod +x /usr/local/sbin/build-nmap.sh
sudo chmod +x /usr/local/sbin/csvlens

if [[ ! -x /usr/local/sbin/configure_ufw_from_csv.sh ]]; then
  echo "[ERROR] Failed to install configure_ufw_from_csv.sh"
  exit 1
fi

if [[ ! -x /usr/local/sbin/validate_users_csv.sh ]]; then
  echo "[ERROR] Failed to install validate_users_csv.sh"
  exit 1
fi

echo "[OK] Firewall scripts installed."

########################################
# INSTALL SYSTEMD Firewall UNITS
########################################

echo "[*] Installing systemd service and timer..."

sudo cp "$REPO_DIR/haas-firewall.service" /etc/systemd/system/
sudo cp "$REPO_DIR/haas-firewall.timer" /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable haas-firewall.service
sudo systemctl enable --now haas-firewall.timer

echo "[OK] Systemd service and timer installed and enabled."
sleep 5

########################################
# Install Nala
########################################
echo "Installing nala"
sudo apt install nala -y
NALA_VERSION=_VERSION=$(nala --version)
echo "[OK] Nala $NALA_VERSION installed."
echo ""
sleep 5

########################################
# Install Fresh Editor
########################################
echo "Installing the Fresh Editor"
sudo https://raw.githubusercontent.com/sinelaw/fresh/refs/heads/master/scripts/install.sh | sh
FRESH_VERSION=$(fresh --version)
echo "[OK] Fresh Editor $FRESH_VERSION installed."
echo ""
sleep 5

########################################
# Install micro text editor
########################################

sudo apt install micro -y
echo ""
MICRO_VERSION=$(micro --version)
echo "[OK] micro text editor $MICRO_VERSION installed."
echo ""
sleep 5

########################################
# Install inetutils-traceroute
########################################
echo "installing inetutils-traceroute"
sudo nala install inetutils-traceroute -y
echo "[OK] inetutils-traceroute installed."
sleep3
echo ""

########################################
# Install nmap
########################################

# sudo /usr/local/sbin/build-nmap.sh
# VERSION=$(nmap --version | head -n1 | awk '{print $3}')
# echo "nmap version $VERSION was successfully installed."
# echo ""
# sleep 5

########################################
# Install Samba Server
########################################

# Update package lists
sudo apt update

# Install Samba
if sudo apt install samba -y; then
    echo "Samba installed successfully"

    # Enable and start Samba services
    sudo systemctl enable --now smbd

    # Create the HaasGroup
    sudo groupadd HaasGroup 2>/dev/null || echo "HaasGroup already exists"

    # Create the haas user and add to HaasGroup
    sudo useradd -m -G HaasGroup haas 2>/dev/null || echo "User haas already exists"

    # Read users from initial_users.csv and create them
    USER_FILE="$REPO_DIR/initial_users.csv"

    if [ -f "$USER_FILE" ]; then
        echo "Reading users from $USER_FILE"

        # Skip header line and read username and password columns
        tail -n +2 "$USER_FILE" | while IFS=',' read -r username password; do
            # Trim whitespace
            username=$(echo "$username" | xargs)
            password=$(echo "$password" | xargs)

            if [ -n "$username" ] && [ -n "$password" ]; then
                echo "Creating user: $username"

                # Create system user and add to HaasGroup. -M don't create home directory.
                # -s /usr/sbin/nologin" No login shell, user is just for Samaba access.
                sudo useradd -M -G HaasGroup -s /usr/sbin/nologin "$username" 2>/dev/null || echo "User $username already exists"

                # Add user to HaasGroup (in case they existed but weren't in the group)
                sudo usermod -aG HaasGroup "$username"

                # Set Samba password non-interactively
                echo -e "$password\n$password" | sudo smbpasswd -a "$username" -s

                echo "User $username created with Samba access"
            fi
        done

        echo ""
        echo =========================================
        echo "All users from initial_users.csv have been processed"
        echo "IMPORTANT: Delete $USER_FILE now for security!"
        echo =========================================
        echo ""
    else
        echo "Warning: initial_users.csv not found at $USER_FILE"
        echo "Skipping initial user creation"
    fi

    # Create the share directory
    sudo mkdir -p /home/haas/Haas_Data_collect
    sudo chown haas:HaasGroup /home/haas/Haas_Data_collect
    sudo chmod 2775 /home/haas/Haas_Data_collect

    # Backup original smb.conf
    sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.backup

    # Create new smb.conf with security hardening
    sudo tee /etc/samba/smb.conf > /dev/null <<EOF
[global]
    workgroup = WORKGROUP
    server string = %h server (Samba, Ubuntu)
    log file = /var/log/samba/log.%m
    max log size = 10000
    logging = file
    panic action = /usr/share/samba/panic-action %d

    # Authentication
    server role = standalone server
    obey pam restrictions = Yes
    unix password sync = Yes
    passwd program = /usr/bin/passwd %u
    passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
    pam password change = Yes
    map to guest = Bad User

    # Protocol Security - Force SMB2/SMB3 only
    client min protocol = SMB2
    client max protocol = SMB3
    server min protocol = SMB2
    server max protocol = SMB3

    # Disable legacy protocols and services
    disable netbios = Yes
    disable spoolss = Yes

    # Disable printing
    load printers = No
    printing = bsd
    printcap name = /dev/null

    [printers]
    available = No
    browseable = No
    printable = Yes

[print$]
    available = No

    # Performance
    socket options = TCP_NODELAY IPTOS_LOWDELAY

[Haas]
    comment = Haas Directory Share
    path = /home/haas/Haas_Data_collect
    read only = no
    browsable = yes
    writable = yes
    public = no
    valid users = @HaasGroup, haas
    force user = haas
    force group = HaasGroup
    create mask = 0664
    force create mode = 0664
    directory mask = 0775
    force directory mode = 0775
EOF

    # Test the configuration
    if sudo testparm -s /etc/samba/smb.conf > /dev/null 2>&1; then
        echo "Samba configuration is valid"
    else
        echo "Warning: Samba configuration may have issues"
        echo "Running testparm for details:"
        sudo testparm -s /etc/samba/smb.conf
    fi

    # Restart Samba to apply changes
    sudo systemctl restart smbd

    echo ""
    echo =========================================
    echo "Samba configured with security hardening:"
    echo "  - SMBv2/SMBv3 only, no SMBv1"
    echo "  - NetBIOS disabled"
    echo "  - Printing disabled"
    echo =========================================
    echo ""
    echo "Samba share 'Haas' configured successfully"
    IP_ADDR=$(hostname -I | awk '{print $1}')
    printf "Share available at: \\\\%s\\Haas\n" "$IP_ADDR"
else
    echo "Failed to install Samba"
    exit 1
fi
echo ""
sleep 5

########################################
# Install Redhat Cockpit for management
########################################

# Update package lists
sudo apt update

# Install Cockpit from backports
if sudo apt install -t noble-backports cockpit -y; then
    echo "Cockpit installed successfully"

    # Enable and start Cockpit
    sudo systemctl enable --now cockpit.socket
    echo "Cockpit is running on https://$(hostname -I | awk '{print $1}'):9090"
else
    echo "Failed to install Cockpit"
    exit 1
fi
sleep 5

########################################
# INSTALL COCKPIT EXTENSION
########################################

COCKPIT_DST="/usr/share/cockpit/haas-firewall"

echo "[*] Installing Cockpit extension to $COCKPIT_DST..."

sudo mkdir -p "$COCKPIT_DST"
sudo cp "$COCKPIT_SRC"/* "$COCKPIT_DST"/

echo "[*] Restarting Cockpit..."
sudo systemctl restart cockpit
echo "[OK] Cockpit extension installed and Cockpit restarted."
sleep 5

########################################
# ENSURE BACKUP DIRECTORY EXISTS
########################################

echo "[*] Ensuring backup directory exists in repo: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

echo "[OK] Backup directory ready."
sleep 5

########################################
# RUN INITIAL FIREWALL CONFIG VIA SYSTEMD
########################################

echo "[*] Running initial firewall configuration via haas-firewall.service..."
sudo systemctl start haas-firewall.service || true

echo ""
echo "=============================================="
echo "[SUCCESS] Haas Firewall installation complete."
echo "=============================================="
echo ""
echo "Repo root:     $REPO_DIR"
echo "CSV Path:      $CSV_PATH"
echo "Backup Dir:    $BACKUP_DIR"
echo "Config File:   $CONFIG_FILE"
echo "Scripts:       /usr/local/sbin/configure_ufw_from_csv.sh"
echo "               /usr/local/sbin/validate_users_csv.sh"
echo "Systemd:       /etc/systemd/system/haas-firewall.service"
echo "               /etc/systemd/system/haas-firewall.timer"
echo "Cockpit UI:    /usr/share/cockpit/haas-firewall/"
echo ""
echo "To enable a Haas subnet later, edit:"
echo "$CONFIG_FILE"
echo ""
echo "set HAAS_MACHINES_SUBNET_V4="" to your CNC machines' IPv4 subnet"
echo "set HAAS_MACHINES_SUBNET_V6="" to your CNC machines' IPv6 subnet (if applicable)"
echo ""
echo "Check firewall status with:"
echo "  sudo ufw status numbered"
echo ""
echo "Current UFW rules:"
sudo ufw status numbered
echo ""
