site_name: Haas-data-collect
site_author: Michael Hubbard (rikosintie)
site_url: https://rikosintie.github.io/Haas_Data_collect/
repo_url: https://github.com/rikosintie/Haas_Data_collect
repo_name: rikosintie/Haas_Data_collect
docs_dir: docs

nav:
  - home: README.md
  - Intro: Introduction.md
  - Python: installing_python.md
  - Usage: usage.md
  - Appliance:
      - Quick Start: 'INSTALL_QUICKSTART.md'
      - Why build an_Appliance: 'build_the_appliance/build_an_appliance.md'
      - Installing Ubuntu: 'build_the_appliance/installing_ubuntu.md'
      - Network Deployment (DHCP/DNS): 'build_the_appliance/network_deployment.md'
      - Creating the Appliance: 'build_the_appliance/configuring_appliance.md'
      - Create HaasGroup and Users: 'build_the_appliance/create-groups.md'
      - Install Samba: 'build_the_appliance/Install_Samba.md'
      - Create Directories-Shares: 'build_the_appliance/directories_shares.md'
      - Update the Appliance: 'build_the_appliance/updating_appliance.md'
      - Firewall Configuration: 'build_the_appliance/firewall_configuration.md'
      - Trouble Shooting: 'build_the_appliance/TS_cockpit.md'
  - Manage the appliance:
      - Introduction: 'manage_the_appliance/manage_intro.md'
      - Firewall Control: 'manage_the_appliance/firewall.md'
      - Manage Samba: 'manage_the_appliance/samba.md'
      - Updates - Logs: 'manage_the_appliance/updates.md'
      - Python Script Services: 'manage_the_appliance/python_scripts.md'
      - Network Visibility (LLDP): 'manage_the_appliance/lldp.md'
      - Terminal Aliases: 'manage_the_appliance/terminal_aliases.md'
      - Third-Party Tools: 'manage_the_appliance/third_party_tools.md'
  - Appendices:
    - Introduction: 'appendices/intro.md'
    - Securing the Appliance: 'appendices/appendix-a.md'
    - File Permissions: 'appendices/appendix-b.md'
    - Threat Model for Auditors: 'appendices/appendix-c.md'
    - Systemd type options: 'appendices/appendix-d.md'
    - SSH Hardening: 'appendices/appendix-e.md'
    - SMB Protocols: 'appendices/appendix-f.md'
    - Troubleshooting: 'appendices/appendix-g.md'
    - Bluetooth keyboard: 'appendices/appendix-h.md'
    - Custom aliases: 'appendices/appendix-i.md'
    - Shell Cheatsheet: 'appendices/appendix-i-cheatsheet.md'
    - Mermaid test: 'appendices/img/stage1.md'


theme:
  name: material
  font:
    text: Ubuntu
    code: Red Hat Mono
  logo: img/ubuntu_icon1.png
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate # (1)!
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  language: en
  favicon: img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  icon:
    admonition:
      info: octicons/info-16
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      success: octicons/check-16
      question: octicons/question-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github

plugins:
    - social
    - search


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rikosintie
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rikosintie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mwhubbard/

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.mark
  - attr_list
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2025 <a href="https://github.com/rikosintie" target="_blank" rel="noopener">Michael Hubbard</a>
